### ISSUE TITLE
confirm population and generator variables are consistent

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/bayeslite#439]
- [x] [94694656025c11e9ea84543294c6235c20170d8d, #441] Make sure the `bayesdb_generator_column` table is populated and matches `bayesdb_variable`, or eliminate it altogether.
- [x] [c3ce5853b8d525145f8386de3bd81afb0493a9a5] Update all callers of `bayesdb_has_variable` and `bayesdb_variable_name` to pass a generator or None, as appropriate.
- [x] [4e0a01ae216018560b43f2360d3a9e72f2c7eba4] Audit all callers of `bayesdb_variable_numbers` and `bayesdb_generator_column_numbers` to make sure they are sensible.
- [x] [#443] Consider eliminating `bayesdb_generator_column_*` in favour of `bayesdb_variable_*`.
- [x] [#444] Confirm every use of `bayesdb_get_generator` checks that the population matches, if appropriate.
- [x] [7eb1dba5fd5d39fea7829f796142b07173e67c33] Simplify multi-line list comprehensions in `compile_simulate`.
- [x] [7eb1dba5fd5d39fea7829f796142b07173e67c33] Simplify multi-line list comprehensions in `CreateTabSim` case in bql.py.
- [x] [#445] Fix detection of statistical type for latent input variables in CGPM schema.  (Can't use `bayesdb_variable_stattype` because it's not a known variable yet -- it's a latent in this schema.)  Or determine that it's a moot point.  Or file a separate issue for it.

**Comment by riastradh-probcomp** [comment]
- [ ] Confirm every use of `bayesdb_get_generator` checks that the population matches, if appropriate.

**Comment by riastradh-probcomp** [comment]
- [ ] Simplify multi-line list comprehensions in `compile_simulate`.
